---

- name: Configure Celeryd service
  template: src=celeryd.conf.j2 dest="/etc/init/{{deploy_app_name}}-celeryd.conf" owner=root group=root mode=0644

- name: Link service configuration
  file: state=link dest={{wsgi_etc_dir}}/{{deploy_app_name}}-celeryd.conf src=/etc/init/{{deploy_app_name}}-celeryd.conf force=yes

- name: Ensure service is started
  service: name={{deploy_app_name}}-celeryd state=started enabled=yes

- name: Configure Celerybeat service
  template: src=celerybeat.conf.j2 dest="/etc/init/{{deploy_app_name}}-celerybeat.conf" owner=root group=root mode=0644

- name: Link service configuration
  file: state=link dest={{wsgi_etc_dir}}/{{deploy_app_name}}-celerybeat.conf src=/etc/init/{{deploy_app_name}}-celerybeat.conf force=yes

- name: Ensure service is started
  service: name={{deploy_app_name}}-celerybeat state=started enabled=yes

- name: Configure flower service
  template: src=flower.conf.j2 dest="/etc/init/{{deploy_app_name}}-flower.conf" owner=root group=root mode=0644

- name: Link service configuration
  file: state=link dest={{wsgi_etc_dir}}/{{deploy_app_name}}-flower.conf src=/etc/init/{{deploy_app_name}}-flower.conf force=yes

- name: Ensure service is started
  service: name={{deploy_app_name}}-flower state=started enabled=yes
