---
- name: Create SSL directory
  file: path={{ciupy3_ssl_dir}} state=directory owner=root
  sudo: yes
  tags: ssl

- name: Copy the certificate
  copy: content="{{''.join(ciupy3_ssl_crt)}}" dest={{ciupy3_ssl_crt_path}} mode=400
  sudo: yes
  tags: ssl
  notify: nginx restart

- name: Copy the key
  copy: content="{{''.join(ciupy3_ssl_key)}}" dest={{ciupy3_ssl_key_path}} mode=400
  sudo: yes
  tags: ssl
  notify: nginx restart
