---

dependencies: []

galaxy_info:
  author: klen
  company: Stouts
  description: Get application source code from git or mercurial repositoires
  license: MIT
  platforms:
  - name: Ubuntu
    versions:
    - all
  categories:
  - cloud
  - development
  - system
  - web
