- name: hostname | Update hostname
  hostname: name="{{hostname_hostname}}"

- name: hostname | Update /etc/hostname
  template: src=hostname.j2 dest=/etc/hostname owner=root group=root mode=0644

- name: hostname | Update /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: "^127.0.0.1"
    line: "127.0.0.1 {{hostname_hostname}}{% if hostname_hostname != hostname_hostname_short %} {{hostname_hostname_short}}{% endif %} localhost"
