---

dependencies: []

galaxy_info:
  author: klen
  company: Stouts
  description: Create deploy directories and deploy variables, also ensure for deploy user exists
  license: MIT
  platforms:
  - name: Ubuntu
    versions:
    - all
  categories:
  - system
