---
wale_enabled: no
django_settings_additional:
  - SENTRY_URL = 'https://231dfbc929db4788838f9215ac70ad2c:af2a20781eff49e38128c17de66166ea@app.getsentry.com/20348'
  - SECRET_KEY = 'something-super-sekrit'
# this is a self signed SSL certificate
ciupy3_ssl_key: |
  -----BEGIN RSA PRIVATE KEY-----
  MIIEowIBAAKCAQEAyV+KdB5mb60sbbjJoCqDJikF5ZRZuAE3hhhYpWBeJBodRHv6
  HLGoJeQhST8A66PYr4fRzzzQ3Z8Nafu6um5iIWS0JovSiSJN70e24DATu971uK2U
  kTTF3Xv5X5//CCECqZN1BSj+XiwIbSu/Pv/ex54HlZ07f53gjZlQLhmPZ2sCoqdi
  5ZH/PIkISkUPwbmqYN4f4/N4PgJJTXdG0oi4Uj7xsmiij/UhjKNdSMg4+E8yyRhr
  e90UmUgtZRsW7MOWVmTp+1qglwDXZ2YOIQdZB9NI8K8RnRUH9jqUSnJle/HXEmQT
  nnCiptbPYM4aGEyQX/F3RuAG5R0IPuZAr0+C/wIDAQABAoIBAGAfReSlujnmjMWX
  Jk9Y2590h4cN6EGn+wv8RRwzwtwyxvOwxjO6Lcxgd+8RruvMGxu2llT4765KRMnp
  SjnBhP/xpPidV5L0GAV20vlymYjdJafQ25Dwgt51VhTqN3922mF9rKcY6UqkdCVA
  c5qr4nigm3g0RHlnMBAHNbm7o7M2DRqjFwQmprcIcHnQlpE1Z/2onkkCFvHGF1yv
  AoDwkr9/TQ+WZNU3xwdOdgiGjWS6i4q0eYjPebvHVbpsAMrqLqv8lo2T52KkybbM
  vELGPTyIhY17NcOpVKVtuCf4wqjCzls4vKxVaMJuT+rRzbs88ivf04kp4A11R4ld
  a5Q0c5ECgYEA8v1Dwqa6EqGGntc/xqgFmYuHPePbI5aRrRJSOv0BT9fBJPFl/1/j
  k+oh2V69gnpH1oT69RebJvCA6vwgRVJ++PIsswQuixx60NmaB53Q7/4LWOXOkGA7
  Ap+Lyqm8FjysigpfCNvtw/6El9ie1XtE3OSC/Phtk3oVEZhxXorFiMcCgYEA1CfU
  jyPqLJoZjN97e5wY5CsFuIFwKb3cq6AyrZx/nKet9E4WcigAwk1cvIsNhTnnHaME
  cajI7tXqzcQ33WdX23X7yMy+9YjTngXmg7SgtDAW23YY5wxEKihSMCjb/zfDRDFt
  PdkSci4ihX5mTgYfl9kyTVr22P7R4TRdUu3IrAkCgYBdAb32+pRMX1FE6UT7CAMk
  s3hvoxCU/aQC5/lbpM3kvsOqHVAaQJy+WCbeqdnF4IIwxTO9rmxvqizeROUhQ6Ng
  LGoZl2ctThhgann/olOAGPBE9alsL7lGlsUOLIvWwyCTscaQgIXwuDIOYRbixc0k
  876Dj595jIgV9RCnzFwxrwKBgGCSYOdnackzvD2r3QG/ZHU4QDpkcTIPAsv8+BSf
  EFe23DBA+2arXu0TWgtZIKZsXQ/YjMVQF2bgaSmRD/zwdcWoRxx4VtRdnDZqaSu6
  pQxgd4cekudZZg3qnL7fWoUqVPBNr3Rfw03GQmCR0O/jSa5NZ+Beb88G73Kb6388
  TgRBAoGBAMNQK5Xkx/CJ/IlIHe8l06ie5DCVyiiDxVQLSUHh1o0Jiq9xxRB0Cpln
  Z3+KbpbQoDCHhi3GkiyGujueqgZkKu3Pwq62ej+UhHivAq7aETmo83l/8k7YPKIT
  OKJgHLyz0iL9vBr+cr0HT00tFGro6lBnkNqYW0O57R/m8H+4OwA8
  -----END RSA PRIVATE KEY-----

ciupy3_ssl_crt: |
  -----BEGIN CERTIFICATE-----
  MIIDuDCCAqACCQCdQW8a7wz1pzANBgkqhkiG9w0BAQUFADCBnTELMAkGA1UEBhMC
  REUxDzANBgNVBAgTBkJlcmxpbjEPMA0GA1UEBxMGQmVybGluMRwwGgYDVQQKExND
  YW4gSSBVc2UgUHl0aG9uIDM/MQwwCgYDVQQLEwNXZWIxHTAbBgNVBAMTFGNhbml1
  c2VweXRob24zLmxvY2FsMSEwHwYJKoZIhvcNAQkBFhJqYW5uaXNAbGVpZGVsLmlu
  Zm8wHhcNMTQwNjA0MDc0MzM4WhcNMTUwNjA0MDc0MzM4WjCBnTELMAkGA1UEBhMC
  REUxDzANBgNVBAgTBkJlcmxpbjEPMA0GA1UEBxMGQmVybGluMRwwGgYDVQQKExND
  YW4gSSBVc2UgUHl0aG9uIDM/MQwwCgYDVQQLEwNXZWIxHTAbBgNVBAMTFGNhbml1
  c2VweXRob24zLmxvY2FsMSEwHwYJKoZIhvcNAQkBFhJqYW5uaXNAbGVpZGVsLmlu
  Zm8wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDJX4p0HmZvrSxtuMmg
  KoMmKQXllFm4ATeGGFilYF4kGh1Ee/ocsagl5CFJPwDro9ivh9HPPNDdnw1p+7q6
  bmIhZLQmi9KJIk3vR7bgMBO73vW4rZSRNMXde/lfn/8IIQKpk3UFKP5eLAhtK78+
  /97HngeVnTt/neCNmVAuGY9nawKip2Llkf88iQhKRQ/Buapg3h/j83g+AklNd0bS
  iLhSPvGyaKKP9SGMo11IyDj4TzLJGGt73RSZSC1lGxbsw5ZWZOn7WqCXANdnZg4h
  B1kH00jwrxGdFQf2OpRKcmV78dcSZBOecKKm1s9gzhoYTJBf8XdG4AblHQg+5kCv
  T4L/AgMBAAEwDQYJKoZIhvcNAQEFBQADggEBALKAGdOOsef14Isn+mQ/gh/2RpsG
  covWGHiv8EigpSfkevyXVpi7ZAUif9NgR/r8Q1csQSLftaWjVnY+wUofkghYlNW1
  wUHLBymCwODM/+H5EudkyikaYpiEeqR5FbSQm/3DGMr8t6dTbYeSDcqgzZtE86/r
  9tKetzxC5RM0LcSqhGtM97dAhn35NyVxrS9SZ696W49CACSRWRVpWEeSHQInyHHo
  MO3tTLS+cjOnVB0da+cGQ0ZrdjnxWIOkgNnhBi4QfmB2Q7NGO5Po1+rhN7pKWotk
  9St68QYfbM4o7qD/OhbExA8hqjx8Aa0FKIeIdR+Lg7qMFqLuKvWP6sQQ3ec=
  -----END CERTIFICATE-----
