---
# vim:sw=2:ft=ansible

- name: Install deb packages
  apt: name={{item}}
  with_items: wsgi_deb_packages 
  tags: [wsgi]

- include: virtualenv.yml
  tags: [wsgi, virtualenv]

- name: Install UWSGI
  pip: name=uWSGI executable={{wsgi_pip}}
  sudo: yes
  sudo_user: "{{wsgi_user}}"

- name: Setup Uwsgi configuration
  template: src=uwsgi.ini.j2 dest={{wsgi_uwsgi_ini}} owner={{wsgi_user}} group={{wsgi_group}}
  notify:
    - uwsgi reload

- name: Configure service
  template: src=upstart.conf.j2 dest=/etc/init/{{wsgi_app_name}}-uwsgi.conf owner=root group=root mode=0644

- name: Link service configuration
  file: state=link dest={{wsgi_etc_dir}}/{{wsgi_app_name}}-uwsgi.conf  src=/etc/init/{{wsgi_app_name}}-uwsgi.conf force=yes

- name: Ensure service is started
  service: name={{wsgi_app_name}}-uwsgi state=started enabled=yes

- name: Compile Nginx configuration
  template: src=nginx.conf.j2 dest={{wsgi_nginx_ini}} owner={{wsgi_user}} group={{wsgi_group}}
  notify:
    - nginx reload

- name: Link nginx config
  file: state=link dest=/etc/nginx/sites-enabled/{{wsgi_app_name}}.conf src={{wsgi_nginx_ini}}
  when: wsgi_nginx_ini != "/etc/nginx/sites-enabled/{{wsgi_app_name}}.conf"

- name: Configure log rotation
  template: src=logrotate.conf.j2 dest=/etc/logrotate.d/{{wsgi_app_name}}.conf
  when: wsgi_log_rotate
